name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "맞춤법 검사"
      uses: TaeHyoungKwon/korean-grammar-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}