name: 'On Pull Request Opened'

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.0.0

  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ohnogumi/auto-reviewers@v0.0.5
        with:
         token: "${{ secrets.GITHUB_TOKEN }}"

  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        with:
          config_path: .github/configs/labeler.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  assign-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: andrefcdias/add-to-milestone@v1.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: "프로그래밍 심리학"

  comment-for-filling-others:
    runs-on: ubuntu-latest
    steps:
    - uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: "적절한 Projects, Milestone, Development를 할당 해주세요~! :bow:"
  
  

